export const navbarLinks = [
  {
    name: "women",
    link: "/women",
    class: "uln b",
  },
  {
    name: "men",
    link: "/men",
    class: "uln b",
  },
  {
    name: "designers",
    link: "/designers",
    class: "uln b",
  },
  {
    name: "search",
    link: "/",
    class: "tool uln g",
  },
  {
    name: " my account",
    link: "/account",
    class: "tool uln g",
  },
  {
    name: "cart (0)",
    link: "/cart",
    class: "tool uln g",
  },
];

export const mockProducts = [
  {
    id: 0,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 1,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 2,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 3,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 4,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 5,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 6,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 7,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 8,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 9,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 10,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 11,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 12,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 13,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 14,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 15,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 16,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 17,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 18,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
  {
    id: 19,
    first_img: "/one.jpg",
    sec_img: "/two.jpg",
    title: "Vintage Horse Portrait Bolo Tie",
    price: "45.00 $",
    prod_link: "/#",
  },
];
